### ISSUE TITLE
Better tables broken in  foundry 0.7.5

### ISSUE THREAD

**Issue by cnutenor** [ultrakorne/better-rolltables#60]
Hello, better tables is one of the best modules created that I know, but unfortunately it is broken in the new stable version of VTT 0.7.5 foundry.
Do you have plans to update this mod? Please!!! :)

**Comment by KevS75** [comment]
Having the same issue, error message form the console pasted below. My players are going to riot soon if they can't roll on their loot tables!! =)

Using Foundry 0.7.5, / DnD5e 0.98 / Better Roll Tables 1.5.1

Uncaught (in promise) TypeError: (intermediate value).roll is not a function
    at RollTable.drawMany (brt-api-changes.js:22)
    at BRTBuilder.rollManyOnTable (brt-builder.js:52)
    at BRTBuilder.betterRoll (brt-builder.js:15)
    at BetterTables.generateChatLoot (better-tables.js:27)
    at HTMLButtonElement.newRollButton.onclick (better-table-view.js:61)

**Comment by ultrakorne** [comment]
sadly i broke the auto update. 
the module version 1.6.x works with foundry 0.7.x

uninstall and reinstall the module (because an auto update is not offered)

**Comment by KevS75** [comment]
Thanks - all working now. Many thanks for getting back to me!
